// Generated by scripts/sync-entrance.mjs from the Quest implementation.
window.MAWARIMI_ENTRANCE_TIMING = Object.freeze({
  "CrackEnd": 0.06,
  "BreakSpan": 0.04,
  "PullBegin": 0.52,
  "PullArrest": 0.12,
  "PullStart": 0.56,
  "BurstTau": 0.024,
  "DriftRate": 0.6,
  "ArriveFirst": 0.7,
  "ArriveSpan": 0.17,
  "PullPowLight": 1.6,
  "PullPowHeavy": 3.5,
  "CloserArrive": 0.9,
  "duration": 5000,
  "shatterAt": 0.02,
  "audioLead": 0.035,
  "screenOnAt": 0.9048162974614119
});
